### ISSUE TITLE
missing ver/data in "@glitchful-dev/sol-apy-sdk": "^3.0.2"

### ISSUE THREAD

**Issue by AC-devon** [glitchful-dev/sol-stake-pool-apy#12]
GM,
Looks like we're missing the latest merge in @glitchful-dev/sol-apy-sdk.

The latest version is: @glitchful-dev/sol-apy-sdk: "^3.0.2"

Checked the DATA_SOURCE array, and it's missing the hubSOL merge.(  HUB_CSV: `${DATA_SOURCE_BASE}hub.csv`)
(and everything related to this merge)

Would really appreciate your help with this. 
Thanks a bunch!

**Comment by janlegner** [comment]
new version has been published
